 -- 2023-04-14
 --서브쿼리
 
 
 -- 스칼라 부속질의 : SELECT 절에 쓸수 있는 서브쿼리, 단일값 (질의의 결과가 단일행 단일열)
 SELECT DEPTNO, (SELECT DNAME FROM DEPT WHERE DEPT.DEPTNO=EMP.DEPTNO) AS DNAME
 FROM EMP
 WHERE ENAME = 'SCOTT';
 
SELECT O.CUSTID , C.NAME , SUM(SALEPRICE)
FROM ORDERS O, CUSTOMER C
WHERE O.CUSTID = C.CUSTID
GROUP BY O.CUSTID, C.NAME;

SELECT O.CUSTID,(SELECT NAME FROM CUSTOMER C WHERE C.CUSTID = O.CUSTID), SUM(O.SALEPRICE),
    (SELECT SYSDATE FROM DUAL)
FROM ORDERS O
GROUP BY O.CUSTID;

-- INLINE VIEW : FROM 절 뒤에 오는 서브퀘리, 가상의 테이블, 테이블처럼 사용

SELECT EMPNO, ENAME, JOB, HIREDATE FROM EMP WHERE DEPTNO = 30;

SELECT * 
FROM (SELECT EMPNO, ENAME, JOB, HIREDATE FROM EMP WHERE DEPTNO = 30)
WHERE ENAME = 'SCOTT'
; 

-- 고객번호가 2 이하인 고객들의 총 판매액
SELECT O.CUSTID, SUM(SALEPRICE) TOTAL
FROM (SELECT CUSTID, NAME FROM CUSTOMER WHERE CUSTID <=2) C, ORDERS O
WHERE C.CUSTID = O.CUSTID
GROUP BY O.CUSTID
;

SELECT ROWNUM, ENAME, HIREDATE
FROM EMP
ORDER BY HIREDATE;

SELECT ENAME, HIREDATE FROM EMP ORDER BY HIREDATE;

SELECT ROWNUM, ENAME , HIREDATE
FROM(SELECT ENAME, HIREDATE FROM EMP ORDER BY HIREDATE)
WHERE ROWNUM<=3 ;

-- EMP 테이블에서 최고 급여를 받는 사람 5명을 뽑아서 사원의 이름과 급여 정보를 출력

SELECT ENAME, SAL
FROM(SELECT ROWNUM, ENAME, SAL FROM EMP ORDER BY SAL DESC)
WHERE ROWNUM <= 5; 


--중첩질의 : WHERE절 뒤에오는 비교연산이나 다른 연산자를 통해 처리할때

--비교 : 단일값이 나오는 서브쿼리를 사용
-- 평균 급여보다 더 많이 받는 사원의 이름과 급여
SELECT AVG(SAL) FROM EMP; --2074

SELECT *
FROM EMP
WHERE SAL> (SELECT AVG(SAL) FROM EMP);

-- 평균 주문금액 이하의 주문에 대해서 주문번호와 금액을 보이시오.
SELECT ORDERID,SALEPRICE
FROM ORDERS
WHERE SALEPRICE <= (SELECT AVG(SALEPRICE) FROM ORDERS);

-- 각 고객의 평균 주문금액보다 큰 금액의 주문 내역에 대해서 주문번호, 고객번호, 금액을 보이시오.

SELECT O1.ORDERID, O1.CUSTID, O1.SALEPRICE
FROM ORDERS O1
WHERE SALEPRICE >(SELECT AVG(SALEPRICE) FROM ORDERS O2 WHERE O2.CUSTID = O1.CUSTID);; -- 고객의 평균 구매액

-- 1번 고객의 평균 구매액
SELECT AVG(SALEPRICE) FROM ORDERS O2 WHERE CUSTID = 1;

-- 3000 이상 받는 사원이 소속된 부서
SELECT DEPTNO FROM EMP WHERE SAL >=3000;
SELECT * FROM EMP WHERE DEPTNO IN (10,20);
 -- 다중행 단일 열 : 10, 20, 20
 
SELECT * FROM EMP WHERE DEPTNO IN (SELECT DISTINCT DEPTNO FROM EMP WHERE SAL >= 3000);

--대한민국에 거주하는 고객에게 판매한 도서의 총 판매액을 구하시오.
SELECT SUM(SALEPRICE)
FROM ORDERS
WHERE CUSTID  IN (SELECT CUSTID FROM CUSTOMER WHERE ADDRESS LIKE '%대한민국%') ;

SELECT SUM(SALEPRICE)
FROM ORDERS O, CUSTOMER C
WHERE O.CUSTID = C.CUSTID
AND C.ADDRESS LIKE ('%대한민국%');

-- 대한민국에 거주하는 고객
SELECT CUSTID FROM CUSTOMER WHERE ADDRESS LIKE '%대한민국%';

SELECT CUSTID FROM CUSTOMER WHERE ADDRESS NOT LIKE '%대한민국%';

-- 3번 고객이 주문한 도서의 최고 금액보다 더 비싼 도서를 구입한 주문의 주문번호와 금액을 보이시오. 
-- ALL : 서브쿼리의 결과 데이터 모두와 비교해서 참일 때 => 참
SELECT ORDERID, SALEPRICE
FROM ORDERS
WHERE  SALEPRICE > ALL(SELECT SALEPRICE FROM ORDERS WHERE CUSTID = 3);
-- SALEPRICE > 6000 AND SALEPRICE > 12000 AND SALEPRICE > 13000

--다음은 부서번호가 30번인 사원들의 급여 중 가장 작은 값(950)보다 많은 급여를 받는 사원의 이름, 급여를 출력
-- SAL > 2850 OR SAL > 1600 OR SAL > 1250 OR SAL >1500 OR SAL > 950
SELECT ENAME , SAL
FROM EMP
WHERE SAL > ANY(SELECT SAL
                FROM EMP
                WHERE DEPTNO = 30);

--30번 소속 사원들 중에서 급여를 가장 많이 받는 사원보다 더 많은 급여를 받는 사람의 이름, 급여를 출력
-- SAL > 2850
SELECT ENAME , SAL
FROM EMP
WHERE SAL > ALL(SELECT SAL FROM EMP WHERE DEPTNO = 30);

--EXISTS , NOT EXISTS
-- 상관관계가 반드시 필요한 서브쿼리가 조건의 결과로 사용 : SELECT의 결과가 존재 하는지 여부에 따라 결과 처리

-- EXISTS 연산자로 대한민국에 거주하는 고객에게 판매한 도서의 총 판매액을 구하시오.
SELECT SUM(SALEPRICE)
FROM ORDERS O
WHERE EXISTS (SELECT *
                FROM CUSTOMER C
                WHERE O.CUSTID = C.CUSTID
                AND ADDRESS LIKE '%대한민국%');
