-- 2023-04-13
-- JOIN

-- CROSS JOIN
-- 스키마를 붙이고 결과 행은 모든 경우의 수 = n*컬럼
SELECT * FROM EMP, DEPT;

--EQUI JOIN
SELECT *
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO;

SELECT E.DEPTNO, D.DEPTNO, DNAME
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO;

--이름이 SCOTT인 사람의 부서명을 출력
SELECT DEPTNO FROM EMP WHERE ENAME = 'SCOTT';
-- 20
SELECT DEPTNO FROM DEPT WHERE DEPTNO = 20;

-- JOIN으로 해결
SELECT ENAME,DNAME
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
      AND E.ENAME = 'SCOTT'; 

-- NON-EQUI JOIN
-- 사원별 급여 등급 표현
SELECT * FROM SALGRADE;

SELECT E.ENAME, S.GRADE, S.LOSAL, E.SAL, S.HISAL
FROM EMP E ,SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
ORDER BY E.SAL;


--SELF JOIN : 자기 자신의 테이블을 조인하는 함수
-- 각 사원의 이름과 각 사원의 매니져 이름을 출력
SELECT E.ENAME ||'의 매니저는'
        || M.ENAME||'입니다'
FROM EMP E , EMP M
WHERE E.MGR = M.EMPNO;

--OUTER JOIN : 조건에 만족하지 않는 행도 출력
SELECT E.ENAME,NVL(M.ENAME,'없음')
FROM EMP E , EMP M
WHERE E.MGR = M.EMPNO(+);

-- ANSI JOIN
SELECT *
FROM EMP CROSS JOIN DEPT;

SELECT *
FROM EMP , DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO;

SELECT *
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;

SELECT *
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;

SELECT * 
FROM EMP JOIN DEPT
USING(DEPTNO);

SELECT *
FROM EMP NATURAL JOIN DEPT;

SELECT DEPTNO
FROM EMP NATURAL JOIN DEPT;

--INNER JOIN
SELECT *
FROM EMP E JOIN EMP M
ON E.MGR = M.EMPNO;
--OUTER JOIN
SELECT *
FROM EMP E LEFT OUTER JOIN EMP M
ON E.MGR = M.EMPNO;

-- 도서 판매 정보 출력
SELECT * FROM ORDERS;

SELECT O.ORDERID,C.NAME,BOOKNAME,O.SALEPRICE,O.ORDERDATE
FROM ORDERS O , CUSTOMER C, BOOK B
WHERE O.CUSTID = C.CUSTID
AND O.BOOKID = B.BOOKID;










