-- 폰북 테이블

--DDL 

-- phoneInfo_basic
CREATE TABLE PHONEINFO_BASIC(
    IDX NUMBER(6) ,
    FR_NAME VARCHAR2(20) CONSTRAINT NL_PHONEINFO_BASIC_FR_NAME NOT NULL,                --친구이름
    FR_PHONENUMBER VARCHAR2(20) CONSTRAINT NL_PHONEINFO_BASIC_FR_PHONENUMBER NOT NULL,  --친구 전화번호
    FR_EMAIL VARCHAR2(20),                                                              --친구 이메일
    FR_ADRESS VARCHAR2(20),                                                             --친구 주소
    FR_REGDATE DATE DEFAULT SYSDATE,                                                    --등록 시간
    CONSTRAINT PK_PHONEINFO_BASIC_IDX PRIMARY KEY(IDX)
    
);

--phoneInfo_univ
CREATE TABLE PHONEINFO_UNIV(
    IDX NUMBER(6),
    FR_U_MAJOR VARCHAR2(20) DEFAULT 'N' CONSTRAINT NL_PHONEINFO_UNIV_FR_U_MAJOR NOT NULL, --대학친구의 전공정보
    FR_U_YEAR NUMBER(1) DEFAULT 1 CONSTRAINT CK_PHONEINFO_UNIV_FR_U_YEAR CHECK (FR_U_YEAR BETWEEN 1 AND 4) NOT NULL,
    FR_REF NUMBER(7) NOT NULL, -- 친구의 기본정보 외래키
    CONSTRAINT PK_PHONEINFO_UNIV_IDX PRIMARY KEY(IDX), 
    CONSTRAINT FK_PHONEINFO_UNIV_FR_U_REF FOREIGN KEY(FR_REF) REFERENCES PHONEINFO_BASIC(IDX)   
);

--phoneInfo_com
CREATE TABLE PHONEINFO_COM(
    IDX NUMBER(6), 
    FR_C_COMPANY VARCHAR2(20)DEFAULT 'N' CONSTRAINT NL_PHONEINIFO_COM_FR_C_COMPANY NOT NULL,  --회사친구의 회사이름
    FR_REF NUMBER(6) NOT NULL, -- 친구의 기본정보 외래키
    CONSTRAINT PK_PHONEINFO_COM_IDX PRIMARY KEY(IDX),
    CONSTRAINT FK_PHONEINFO_COM_FR_REF FOREIGN KEY(FR_REF) REFERENCES PHONEINFO_BASIC(IDX)
);
DESC PHONEINFO_BASIC;
DESC PHONEINFO_UNIV;
DESC PHONEINFO_COM;

DROP TABLE PHONEINFO_BASIC;
DROP TABLE PHONEINFO_UNIV;
DROP TABLE PHONEINFO_COM;


--1. phoneInfo_basic 테이블의 SELECT, UPDATE, DELETE, INSERT 하는 SQL

--2. phoneinfo_univ 테이블의 SELECT, UPDATE, DELETE, INSERT 하는 SQL

--3. phoneinfo_com 테이블의 SELECT, UPDATE, DELETE, INSERT 하는 SQL
